package net.vitki.rtf;


public interface DrawConst
{
    public static final int D_FREEFORM              = 0;   // Freeform or non-autoshape
    public static final int D_RECTANGLE             = 1;   // Rectangle
    public static final int D_ROUND_RECTANGLE       = 2;   // Round rectangle
    public static final int D_ELLIPSE               = 3;   // Ellipse
    public static final int D_DIAMOND               = 4;   // Diamond
    public static final int D_ISOSCELES_TRIANGLE    = 5;   // Isosceles triangle
    public static final int D_RT_TRIANGLE           = 6;   // Right triangle
    public static final int D_PARALLELOGRAM         = 7;   // Parallelogram
    public static final int D_TRAPEZOID             = 8;   // Trapezoid
    public static final int D_HEXAGON               = 9;   // Hexagon
    public static final int D_OCTAGON               = 10;  // Octagon
    public static final int D_PLUS_SIGN             = 11;  // Plus Sign
    public static final int D_STAR                  = 12;  // Star
    public static final int D_ARROW                 = 13;  // Arrow
    public static final int D_THICK_ARROW           = 14;  // Thick arrow
    public static final int D_HOME_PLATE            = 15;  // Home plate
    public static final int D_CUBE                  = 16;  // Cube
    public static final int D_BALLOON               = 17;  // Balloon
    public static final int D_SEAL                  = 18;  // Seal
    public static final int D_ARC                   = 19;  // Arc
    public static final int D_LINE                  = 20;  // Line
    public static final int D_PLAQUE                = 21;  // Plaque
    public static final int D_CAN                   = 22;  // Can
    public static final int D_DONUT                 = 23;  // Donut
    public static final int D_TEXT_SIMPLE           = 24;  // Text simple
    public static final int D_TEXT_OCTAGON          = 25;  // Text octagon
    public static final int D_TEXT_HEXAGON          = 26;  // Text hexagon
    public static final int D_TEXT_CURVE            = 27;  // Text curve
    public static final int D_TEXT_WAVE             = 28;  // Text wave
    public static final int D_TEXT_RING             = 29;  // Text ring
    public static final int D_TEXT_ON_CURVE         = 30;  // Text on curve
    public static final int D_TEXT_ON_RING          = 31;  // Text on ring
    public static final int D_CO_1                  = 41;  // Callout 1
    public static final int D_CO_2                  = 42;  // Callout 2
    public static final int D_CO_3                  = 43;  // Callout 3
    public static final int D_ACCENT_CO_1           = 44;  // Accent callout 1
    public static final int D_ACCENT_CO_2           = 45;  // Accent callout 2
    public static final int D_ACCENT_CO_3           = 46;  // Accent callout 3
    public static final int D_BORDER_CO_1           = 47;  // Border callout 1
    public static final int D_BORDER_CO_2           = 48;  // Border callout 2
    public static final int D_BORDER_CO_3           = 49;  // Border callout 3
    public static final int D_ACCENT_BORDER_CO_1    = 50;  // Accent border callout 1
    public static final int D_ACCENT_BORDER_CO_2    = 51;  // Accent border callout 2
    public static final int D_ACCENT_BORDER_CO_3    = 52;  // Accent border callout 3
    public static final int D_RIBBON                = 53;  // Ribbon
    public static final int D_RIBBON2               = 54;  // Ribbon2
    public static final int D_CHEVRON               = 55;  // Chevron
    public static final int D_PENTAGON              = 56;  // Pentagon
    public static final int D_NO_SMOKING            = 57;  // No smoking
    public static final int D_SEAL8                 = 58;  // Seal8
    public static final int D_SEAL16                = 59;  // Seal16
    public static final int D_SEAL32                = 60;  // Seal32
    public static final int D_WEDGE_RECTANGLE_CO    = 61;  // Wedge rectangle callout
    public static final int D_WEDGE_RRECT_CO        = 62;  // Wedge RRect callout
    public static final int D_WEDGE_ELLIPSE_CO      = 63;  // Wedge ellipse callout
    public static final int D_WAVE                  = 64;  // Wave
    public static final int D_FOLDED_CORNER         = 65;  // Folded corner
    public static final int D_LT_ARROW              = 66;  // Left arrow
    public static final int D_DN_ARROW              = 67;  // Down arrow
    public static final int D_UP_ARROW              = 68;  // Up arrow
    public static final int D_LT_RT_ARROW           = 69;  // Left right arrow
    public static final int D_UP_DN_ARROW           = 70;  // Up down arrow
    public static final int D_IRREGULARSEAL1        = 71;  // IrregularSeal1
    public static final int D_IRREGULARSEAL2        = 72;  // IrregularSeal2
    public static final int D_LIGHTNING_BOLT        = 73;  // Lightning bolt
    public static final int D_HEART                 = 74;  // Heart
    public static final int D_PICTURE_FRAME         = 75;  // Picture frame
    public static final int D_QUAD_ARROW            = 76;  // Quad arrow
    public static final int D_LT_ARROW_CO           = 77;  // Left arrow callout
    public static final int D_RT_ARROW_CO           = 78;  // Right arrow callout
    public static final int D_UP_ARROW_CO           = 79;  // Up arrow callout
    public static final int D_DN_ARROW_CO           = 80;  // Down arrow callout
    public static final int D_LT_RT_ARROW_CO        = 81;  // Left right arrow callout
    public static final int D_UP_DN_ARROW_CO        = 82;  // Up down arrow callout
    public static final int D_QUAD_ARROW_CO         = 83;  // Quad arrow callout
    public static final int D_BEVEL                 = 84;  // Bevel
    public static final int D_LT_BRACKET            = 85;  // Left bracket
    public static final int D_RT_BRACKET            = 86;  // Right bracket
    public static final int D_LT_BRACE              = 87;  // Left brace
    public static final int D_RT_BRACE              = 88;  // Right brace
    public static final int D_LT_UP_ARROW           = 89;  // Left up arrow
    public static final int D_BENT_UP_ARROW         = 90;  // Bent up arrow
    public static final int D_BENT_ARROW            = 91;  // Bent arrow
    public static final int D_SEAL24                = 92;  // Seal24
    public static final int D_STRIPED_RT_ARROW      = 93;  // Striped right arrow
    public static final int D_NOTCHED_RT_ARROW      = 94;  // Notched right arrow
    public static final int D_BLOCK_ARC             = 95;  // Block arc
    public static final int D_SMILEY_FACE           = 96;  // Smiley face
    public static final int D_VERT_SCROLL           = 97;  // Vertical scroll
    public static final int D_HOR_SCROLL            = 98;  // Horizontal scroll
    public static final int D_CIRCULAR_ARROW        = 99;  // Circular arrow
    public static final int D_NOTCHED_CIRC_ARROW    = 100; // Notched circular arrow
    public static final int D_U_TURN_ARROW          = 101; // U-turn arrow
    public static final int D_CURVED_RT_ARROW       = 102; // Curved right arrow
    public static final int D_CURVED_LT_ARROW       = 103; // Curved left arrow
    public static final int D_CURVED_UP_ARROW       = 104; // Curved up arrow
    public static final int D_CURVED_DN_ARROW       = 105; // Curved down arrow
    public static final int D_CLOUD_CO              = 106; // Cloud callout
    public static final int D_ELLIPSE_RIBBON        = 107; // Ellipse ribbon
    public static final int D_ELLIPSE_RIBBON_2      = 108; // Ellipse ribbon 2
    public static final int D_FCHART_PROCESS        = 109; // Flow chart process
    public static final int D_FCHART_DECISION       = 110; // Flow chart decision
    public static final int D_FCHART_INPUT_OUTPUT   = 111; // Flow chart input output
    public static final int D_FCHART_PREDEF_PROC    = 112; // Flow chart predefined process
    public static final int D_FCHART_INTERN_STOR    = 113; // Flow chart internal storage
    public static final int D_FCHART_DOCUMENT       = 114; // Flow chart document
    public static final int D_FCHART_MULTIDOC       = 115; // Flow chart multidocument
    public static final int D_FCHART_TERMINATOR     = 116; // Flow chart terminator
    public static final int D_FCHART_PREPARATION    = 117; // Flow chart preparation
    public static final int D_FCHART_MANUAL_INPUT   = 118; // Flow chart manual input
    public static final int D_FCHART_MANUAL_OP      = 119; // Flow chart manual operation
    public static final int D_FCHART_CONNECTOR      = 120; // Flow chart connector
    public static final int D_FCHART_PUNCHED_CARD   = 121; // Flow chart punched card
    public static final int D_FCHART_PUNCHED_TAPE   = 122; // Flow chart punched tape
    public static final int D_FCHART_SUM_JUNCT      = 123; // Flow chart summing junction
    public static final int D_FCHART_OR             = 124; // Flow chart or
    public static final int D_FCHART_COLLATE        = 125; // Flow chart collate
    public static final int D_FCHART_SORT           = 126; // Flow chart sort
    public static final int D_FCHART_EXTRACT        = 127; // Flow chart extract
    public static final int D_FCHART_MERGE          = 128; // Flow chart merge
    public static final int D_FCHART_OFFL_STORAGE   = 129; // Flow chart offline storage
    public static final int D_FCHART_ONLN_STORAGE   = 130; // Flow chart online storage
    public static final int D_FCHART_MAGNETIC_TAPE  = 131; // Flow chart magnetic tape
    public static final int D_FCHART_MAGNETIC_DISK  = 132; // Flow chart magnetic disk
    public static final int D_FCHART_MAGNETIC_DRUM  = 133; // Flow chart magnetic drum
    public static final int D_FCHART_DISPLAY        = 134; // Flow chart display
    public static final int D_FCHART_DELAY          = 135; // Flow chart delay
    public static final int D_TEXT_PLAIN_TEXT       = 136; // Text plain text
    public static final int D_TEXT_STOP             = 137; // Text stop
    public static final int D_TEXT_TRIANGLE         = 138; // Text triangle
    public static final int D_TEXT_TRIANGLE_INV     = 139; // Text triangle inverted
    public static final int D_TEXT_CHEVRON          = 140; // Text chevron
    public static final int D_TEXT_CHEVRON_INV      = 141; // Text chevron inverted
    public static final int D_TEXT_RING_INSIDE      = 142; // Text ring inside
    public static final int D_TEXT_RING_OUTSIDE     = 143; // Text ring outside
    public static final int D_TEXT_ARCH_UP_CURVE    = 144; // Text arch up curve
    public static final int D_TEXT_ARCH_DN_CURVE    = 145; // Text arch down curve
    public static final int D_TEXT_CIRCLE_CURVE     = 146; // Text circle curve
    public static final int D_TEXT_BUTTON_CURVE     = 147; // Text button curve
    public static final int D_TEXT_ARCH_UP_POUR     = 148; // Text arch up pour
    public static final int D_TEXT_ARCH_DN_POUR     = 149; // Text arch down pour
    public static final int D_TEXT_CIRCLE_POUR      = 150; // Text circle pour
    public static final int D_TEXT_BUTTON_POUR      = 151; // Text button pour
    public static final int D_TEXT_CURVE_UP         = 152; // Text curve up
    public static final int D_TEXT_CURVE_DN         = 153; // Text curve down
    public static final int D_TEXT_CASCADE_UP       = 154; // Text cascade up
    public static final int D_TEXT_CASCADE_DN       = 155; // Text cascade down
    public static final int D_TEXT_WAVE1            = 156; // Text wave1
    public static final int D_TEXT_WAVE2            = 157; // Text wave2
    public static final int D_TEXT_WAVE3            = 158; // Text wave3
    public static final int D_TEXT_WAVE4            = 159; // Text wave4
    public static final int D_TEXT_INFL             = 160; // Text inflate
    public static final int D_TEXT_DEFL             = 161; // Text deflate
    public static final int D_TEXT_INFL_BTM         = 162; // Text inflate bottom
    public static final int D_TEXT_DEFL_BTM         = 163; // Text deflate bottom
    public static final int D_TEXT_INFL_TOP         = 164; // Text inflate top
    public static final int D_TEXT_DEFL_TOP         = 165; // Text deflate top
    public static final int D_TEXT_DEFL_INFL        = 166; // Text deflate inflate
    public static final int D_TEXT_DEFL_INFL_DEFL   = 167; // Text deflate inflate deflate
    public static final int D_TEXT_FADE_RT          = 168; // Text fade right
    public static final int D_TEXT_FADE_LT          = 169; // Text fade left
    public static final int D_TEXT_FADE_UP          = 170; // Text fade up
    public static final int D_TEXT_FADE_DN          = 171; // Text fade down
    public static final int D_TEXT_SLANT_UP         = 172; // Text slant up
    public static final int D_TEXT_SLANT_DN         = 173; // Text slant down
    public static final int D_TEXT_CAN_UP           = 174; // Text can up
    public static final int D_TEXT_CAN_DN           = 175; // Text can down
    public static final int D_FCHART_ALT_PROCESS    = 176; // Flow chart alternate process
    public static final int D_FCHART_OFFP_CONN      = 177; // Flow chart off-page connector
    public static final int D_CO_90                 = 178; // Callout 90
    public static final int D_ACCENT_CO_90          = 179; // Accent callout 90
    public static final int D_BORDER_CO_90          = 180; // Border callout 90
    public static final int D_ACCENT_BORDER_CO_90   = 181; // Accent border callout 90
    public static final int D_LT_RT_UP_ARROW        = 182; // Left right up arrow
    public static final int D_SUN                   = 183; // Sun
    public static final int D_MOON                  = 184; // Moon
    public static final int D_BRACKET_PAIR          = 185; // Bracket pair
    public static final int D_BRACE_PAIR            = 186; // Brace pair
    public static final int D_SEAL4                 = 187; // Seal4
    public static final int D_DOUBLE_WAVE           = 188; // Double wave
    public static final int D_HOST_CONTROL          = 201; // Host control
    public static final int D_TEXT_BOX              = 202; // Text box

    // Horizontal alignment:
    public static final int HALIGN_LEFT    = 1;
    public static final int HALIGN_CENTER  = 2;
    public static final int HALIGN_RIGHT   = 3;
    public static final int HALIGN_INSIDE  = 4;
    public static final int HALIGN_OUTSIDE = 5;
    
    // Position horizontally relative to:
    public static final int HPOS_MARGIN    = 0;
    public static final int HPOS_PAGE      = 1;
    public static final int HPOS_COLUMN    = 2;
    public static final int HPOS_CHARACTER = 3;
    
    // Vertical alignment:
    public static final int VALIGN_CENTER  = 1;
    public static final int VALIGN_COLUMN  = 2;
    public static final int VALIGN_BOTTOM  = 3;
    public static final int VALIGN_INSIDE  = 4;
    public static final int VALIGN_OUTSIDE = 5;
    
    // Position vertically relative to:
    public static final int VPOS_MARGIN    = 0;
    public static final int VPOS_PAGE      = 1;
    public static final int VPOS_PARAGRAPH = 2;
    public static final int VPOS_LINE      = 3;
    
    // Wrap text at shape margins:
    public static final int TEXT_WRAP_SQUARE     = 0;
    public static final int TEXT_WRAP_TIGHT      = 1;
    public static final int TEXT_WRAP_NONE       = 2;
    public static final int TEXT_WRAP_TOP_BOTTOM = 3;
    public static final int TEXT_WRAP_THROUGH    = 4;
    
    // Text anchor point:
    public static final int TEXT_ANCHOR_TOP           = 0;
    public static final int TEXT_ANCHOR_MIDDLE        = 1;
    public static final int TEXT_ANCHOR_BOTTOM        = 2;
    public static final int TEXT_ANCHOR_TOP_CENTER    = 3;
    public static final int TEXT_ANCHOR_MIDDLE_CENTER = 4;
    public static final int TEXT_ANCHOR_BOTTOM_CENTER = 5;
    public static final int TEXT_ANCHOR_B_C_BASELINE  = 6;
    
    // Text flow:
    public static final int TEXT_FLOW_HOR_NONASCIIT       = 0;
    public static final int TEXT_FLOW_TOP_BOTTOM_ASCII    = 1;
    public static final int TEXT_FLOW_BOTTOM_TOP_NONASCII = 2;
    public static final int TEXT_FLOW_TOP_BOTTOM_NONASCII = 3;
    public static final int TEXT_FLOW_HOR_ASCII           = 4;
    
    // Font rotation:
    public static final int FONT_ROT_RIGHT = 0;
    public static final int FONT_ROT_DOWN  = 1;
    public static final int FONT_ROT_LEFT  = 2;
    public static final int FONT_ROT_UP    = 3;
    
    // Alignment on curve:
    public static final int CURVE_ALIGN_STRETCH        = 0;
    public static final int CURVE_ALIGN_CENTER         = 1;
    public static final int CURVE_ALIGN_LEFT_JUSTIFY   = 2;
    public static final int CURVE_ALIGN_RIGHT_JUSTIFY  = 3;
    public static final int CURVE_ALIGN_SPREAD_LETTERS = 4;
    public static final int CURVE_ALIGN_SPREAD_WORDS   = 5;
    
    // Type of fill:
    public static final int FILL_SOLID           = 0;
    public static final int FILL_PATTERN         = 1;
    public static final int FILL_TEXTURE         = 2;
    public static final int FILL_PICTURE         = 3;
    public static final int FILL_SHADE_START     = 4;
    public static final int FILL_SHADE_BOUNDING  = 5;
    public static final int FILL_SHADE_OUTLINE   = 6;
    public static final int FILL_SHADE_FILLANGLE = 7;
    
    // Type of line:
    public static final int LINE_SOLID   = 0;
    public static final int LINE_PATTERN = 1;
    public static final int LINE_TEXTURE = 2;
    public static final int LINE_PICTURE = 3;
    
    // Line style:
    public static final int LINES_SINGLE     = 0;
    public static final int LINES_DOUBLE     = 1;
    public static final int LINES_THICK_THIN = 2;
    public static final int LINES_THIN_THICK = 3;
    public static final int LINES_TRIPLE     = 4;
    
    // Dashing:
    public static final int DASH_SOLID              = 0;
    public static final int DASH_DASH               = 1;
    public static final int DASH_DOT                = 2;
    public static final int DASH_DASH_DOT           = 3;
    public static final int DASH_DASH_DOT_DOT       = 4;
    public static final int DASH_DOT_LINE           = 6;
    public static final int DASH_DASH_LINE          = 7;
    public static final int DASH_LONG_DASH          = 8;
    public static final int DASH_DASH_DOT_LINE      = 9;
    public static final int DASH_LONG_DASH_DOT      = 10;
    public static final int DASH_LONG_DASH_DOT_DOT  = 11;
    
    // Start arrow type:
    public static final int ARROW_NOTHING     = 0;
    public static final int ARROW_ARROW       = 1;
    public static final int ARROW_STEALTH     = 2;
    public static final int ARROW_DIAMOND     = 3;
    public static final int ARROW_OVAL        = 4;
    public static final int ARROW_OPEN        = 6;
    public static final int ARROW_CHEVRON     = 7;
    public static final int ARROW_DBL_CHEVRON = 8;
    
    // Start arrow width:
    public static final int ARROW_WIDE_NARROW = 0;
    public static final int ARROW_WIDE_MEDIUM = 1;
    public static final int ARROW_WIDE_WIDE   = 2;
    
    // Start arrow length:
    public static final int ARROW_LEN_SHORT   = 0;
    public static final int ARROW_LEN_MEDIUM  = 1;
    public static final int ARROW_LEN_LONG    = 2;
    
    // Line cap style for shape:
    public static final int LINE_CAP_ROUND  = 0;
    public static final int LINE_CAP_SQUARE = 1;
    public static final int LINE_CAP_FLAT   = 2;
    
    // Measurement type:
    public static final int MEAS_DEFAULT          = 0;
    public static final int MEAS_EMUS             = 1;
    public static final int MEAS_PIXELS           = 2;
    public static final int MEAS_FIX_FRACTION     = 3;
    public static final int MEAS_RATIO_FIX        = 4;
    public static final int MEAS_EMU_FIX_RATIO    = 5;
    public static final int MEAS_PX_FIX_RATIO     = 6;
    public static final int MEAS_PROPORTION       = 7;
    public static final int MEAS_FAVOR_LARGE_SIZE = 8;
    public static final int MEAS_EMU_FIX_RATIO_2  = 9;
    public static final int MEAS_PX_FIX_RATIO_2   = 10;
    public static final int MEAS_PROPORTION_2     = 11;
    
    // Line join style for shape:
    public static final int JOIN_STRAIGHT = 0;
    public static final int JOIN_EXTEND   = 1;
    public static final int JOIN_ARC      = 2;
    
    // Type of shadow:
    public static final int SHADOW_OFFSET        = 0;
    public static final int SHADOW_DOUBLE_OFFSET = 1;
    public static final int SHADOW_RICH_RELATIVE = 2;
    public static final int SHADOW_RICH_IN_SPACE = 3;
    public static final int SHADOW_PERSPECTIVE   = 4;
    public static final int SHADOW_EMBOSS        = 6;
    
    // Rendering:
    public static final int RENDER_DETAIL    = 0;
    public static final int RENDER_WIREFRAME = 1;
    public static final int RENDER_BOUNDING  = 2;
    
    // Where transform applies:
    public static final int TRANSFORM_ABSOLUTE = 0;
    public static final int TRANSFORM_SHAPE    = 1;
    public static final int TRANSFORM_DRAWING  = 2;
    
    // Callout type:
    public static final int CALLOUT_ANGLE90 = 1;
    public static final int CALLOUT_1SEG    = 2;
    public static final int CALLOUT_2SEGS   = 3;
    public static final int CALLOUT_3SEGS   = 4;
    
    // Callout angle:
    public static final int CO_ANGLE_ANY = 1;
    public static final int CO_ANGLE_30  = 2;
    public static final int CO_ANGLE_43  = 3;
    public static final int CO_ANGLE_60  = 4;
    public static final int CO_ANGLE_90  = 5;
    
    // Callout drop type:
    public static final int CO_DROP_TOP       = 0;
    public static final int CO_DROP_CENTER    = 1;
    public static final int CO_DROP_BOTTOM    = 2;
    public static final int CO_DROP_SPECIFIED = 3;
    
    // Connection site type:
    public static final int CONN_SITE_NONE     = 0;
    public static final int CONN_SITE_SEGMENTS = 1;
    public static final int CONN_SITE_CUSTOM   = 2;
    public static final int CONN_SITE_RECT     = 3;
    
    // Connector style:
    public static final int CONN_STYLE_STRAIGHT = 0;
    public static final int CONN_STYLE_BENT     = 1;
    public static final int CONN_STYLE_CURVED   = 2;
    public static final int CONN_STYLE_NONE     = 3;
    
    // Modifications made in different forms of black and white mode:
    public static final int BW_COLOR            =  0;
    public static final int BW_AUTOMATIC        =  1;
    public static final int BW_GRAYSCALE        =  2;
    public static final int BW_LIGHT_GRAYSCALE  =  3;
    public static final int BW_INVERSE_GRAY     =  4;
    public static final int BW_GRAY_OUTLINE     =  5;
    public static final int BW_BLACK_TEXTLINE   =  6;
    public static final int BW_HIGH_CONTRAST    =  7;
    public static final int BW_BLACK            =  8;
    public static final int BW_WHITE            =  9;
    public static final int BW_DONT_SHOW        = 10;    

    /*=== Tag Definitions===*/

    public static final int _posh                       = 1 ;
    public static final int _posrelh                    = 2 ;
    public static final int _posv                       = 3 ;
    public static final int _posrelv                    = 4 ;
    public static final int _fLayoutInCell              = 5 ;
    public static final int _fAllowOverlap              = 6 ;
    public static final int _fChangePage                = 7 ;
    public static final int _fIsBullet                  = 8 ;
    public static final int _Rotation                   = 9 ;
    public static final int _fFlipV                     = 10  ;
    public static final int _fFlipH                     = 11  ;
    public static final int _ShapeType                  = 12  ;
    public static final int _wzName                     = 13  ;
    public static final int _pWrapPolygonVertices       = 14  ;
    public static final int _dxWrapDistLeft             = 15  ;
    public static final int _dyWrapDistTop              = 16  ;
    public static final int _dxWrapDistRight            = 17  ;
    public static final int _dyWrapDistBottom           = 18  ;
    public static final int _fBehindDocument            = 19  ;
    public static final int _fIsButton                  = 20  ;
    public static final int _fHidden                    = 21  ;
    public static final int _pihlShape                  = 22  ;
    public static final int _fArrowheadsOK              = 23  ;
    public static final int _fBackground                = 24  ;
    public static final int _fDeleteAttachedObject      = 25  ;
    public static final int _fEditedWrap                = 26  ;
    public static final int _fHitTestFill               = 28  ;
    public static final int _fHitTestLine               = 29  ;
    public static final int _fInitiator                 = 30  ;
    public static final int _fNoFillHitTest             = 31  ;
    public static final int _fNoHitTestPicture          = 32  ;
    public static final int _fNoLineDrawDash            = 33  ;
    public static final int _fOleIcon                   = 34  ;
    public static final int _fOnDblClickNotify          = 35  ;
    public static final int _fOneD                      = 36  ;
    public static final int _fPreferRelativeResize      = 37  ;
    public static final int _fPrint                     = 38  ;
    public static final int _hspMaster                  = 39  ;
    public static final int _hspNext                    = 40  ;
    public static final int _xLimo                      = 41  ;
    public static final int _yLimo                      = 42  ;
    public static final int _fLockRotation              = 43  ;
    public static final int _fLockAspectRatio           = 44  ;
    public static final int _fLockAgainstSelect         = 45  ;
    public static final int _fLockCropping              = 46  ;
    public static final int _fLockVerticies             = 47  ;
    public static final int _fLockText                  = 48  ;
    public static final int _fLockAdjustHandles         = 49  ;
    public static final int _fLockAgainstGrouping       = 50  ;
    public static final int _fLockShapeType             = 51  ;
    public static final int _dxTextLeft                 = 52  ;
    public static final int _dyTextTop                  = 53  ;
    public static final int _dxTextRight                = 54  ;
    public static final int _dyTextBottom               = 55  ;
    public static final int _WrapText                   = 56  ;
    public static final int _anchorText                 = 57  ;
    public static final int _txflTextFlow               = 58  ;
    public static final int _cdirFont                   = 59  ;
    public static final int _fAutoTextMargin            = 60  ;
    public static final int _scaleText                  = 61  ;
    public static final int _lTxid                      = 62  ;
    public static final int _fRotateText                = 63  ;
    public static final int _fSelectText                = 64  ;
    public static final int _fFitShapeToText            = 65  ;
    public static final int _fFitTextToShape            = 66  ;
    public static final int _gtextUNICODE               = 67  ;
    public static final int _gtextAlign                 = 68  ;
    public static final int _gtextSize                  = 69  ;
    public static final int _gtextSpacing               = 70  ;
    public static final int _gtextFont                  = 71  ;
    public static final int _fGtext                     = 72  ;
    public static final int _gtextFVertical             = 73  ;
    public static final int _gtextFKern                 = 74  ;
    public static final int _gtextFTight                = 75  ;
    public static final int _gtextFStretch              = 76  ;
    public static final int _gtextFShrinkFit            = 77  ;
    public static final int _gtextFBestFit              = 78  ;
    public static final int _gtextFNormalize            = 79  ;
    public static final int _gtextFDxMeasure            = 80  ;
    public static final int _gtextFBold                 = 81  ;
    public static final int _gtextFItalic               = 82  ;
    public static final int _gtextFUnderline            = 83  ;
    public static final int _gtextFShadow               = 84  ;
    public static final int _gtextFSmallcaps            = 85  ;
    public static final int _gtextFStrikethrough        = 86  ;
    public static final int _fGtextOK                   = 87  ;
    public static final int _gtextFReverseRows          = 88  ;
    public static final int _gtextRTF                   = 89  ;
    public static final int _cropFromTop                = 90  ;
    public static final int _cropFromBottom             = 91  ;
    public static final int _cropFromLeft               = 92  ;
    public static final int _cropFromRight              = 93  ;
    public static final int _pib                        = 94  ;
    public static final int _pibName                    = 95  ;
    public static final int _pibFlags                   = 96  ;
    public static final int _pictureTransparent         = 97  ;
    public static final int _pictureContrast            = 98  ;
    public static final int _PictureBrightness          = 99  ;
    public static final int _pictureGamma               = 100 ;
    public static final int _pictureGray                = 101 ;
    public static final int _pictureBiLevel             = 102 ;
    public static final int _pibPrint                   = 103 ;
    public static final int _pibPrintFlags              = 104 ;
    public static final int _pibPrintName               = 105 ;
    public static final int _pictureActive              = 106 ;
    public static final int _pictureDblCrMod            = 107 ;
    public static final int _pictureFillCrMod           = 108 ;
    public static final int _pictureId                  = 109 ;
    public static final int _pictureLineCrMod           = 110 ;
    public static final int _geoLeft                    = 111 ;
    public static final int _geoTop                     = 112 ;
    public static final int _geoRight                   = 113 ;
    public static final int _geoBottom                  = 114 ;
    public static final int _pVerticies                 = 115 ;
    public static final int _pSegmentInfo               = 116 ;
    public static final int _pFragments                 = 117 ;
    public static final int _pGuides                    = 118 ;
    public static final int _pInscribe                  = 119 ;
    public static final int _pAdjustHandles             = 120 ;
    public static final int _adjustValue                = 121 ;
    public static final int _adjust2Value               = 122 ;
    public static final int _adjust3Value               = 123 ;
    public static final int _adjust4Value               = 124 ;
    public static final int _adjust5Value               = 125 ;
    public static final int _adjust6Value               = 126 ;
    public static final int _adjust7Value               = 127 ;
    public static final int _adjust8Value               = 128 ;
    public static final int _adjust9Value               = 129 ;
    public static final int _adjust10Value              = 130 ;
    public static final int _fRelChangePage             = 131 ;
    public static final int _fRelFlipH                  = 132 ;
    public static final int _fRelFlipV                  = 133 ;
    public static final int _groupBottom                = 134 ;
    public static final int _groupLeft                  = 135 ;
    public static final int _groupRight                 = 136 ;
    public static final int _groupTop                   = 137 ;
    public static final int _relBottom                  = 138 ;
    public static final int _relLeft                    = 139 ;
    public static final int _relRight                   = 140 ;
    public static final int _relRotation                = 141 ;
    public static final int _relTop                     = 142 ;
    public static final int _lidRegroup                 = 143 ;
    public static final int _fillType                   = 144 ;
    public static final int _fillColor                  = 145 ;
    public static final int _fillOpacity                = 146 ;
    public static final int _fillBackColor              = 147 ;
    public static final int _fillBackOpacity            = 148 ;
    public static final int _fillBlip                   = 149 ;
    public static final int _fillBlipName               = 150 ;
    public static final int _fillblipflags              = 151 ;
    public static final int _fillWidth                  = 152 ;
    public static final int _fillHeight                 = 153 ;
    public static final int _fillAngle                  = 154 ;
    public static final int _fillFocus                  = 155 ;
    public static final int _fillToLeft                 = 156 ;
    public static final int _fillToTop                  = 157 ;
    public static final int _fillToRight                = 158 ;
    public static final int _fillToBottom               = 159 ;
    public static final int _fillShadeColors            = 160 ;
    public static final int _fillOriginX                = 161 ;
    public static final int _fillOriginY                = 162 ;
    public static final int _fillShapeOriginX           = 163 ;
    public static final int _fillShapeOriginY           = 164 ;
    public static final int _fFilled                    = 165 ;
    public static final int _fillCrMod                  = 166 ;
    public static final int _fillDztype                 = 167 ;
    public static final int _fillRectBottom             = 168 ;
    public static final int _fillRectLeft               = 169 ;
    public static final int _fillRectRight              = 170 ;
    public static final int _fillRectTop                = 171 ;
    public static final int _fillShadePreset            = 173 ;
    public static final int _fillShadeType              = 174 ;
    public static final int _fillShape                  = 175 ;
    public static final int _fillUseRect                = 176 ;
    public static final int _fFillOK                    = 178 ;
    public static final int _fFillShadeShapeOK          = 179 ;
    public static final int _lineColor                  = 180 ;
    public static final int _lineBackColor              = 181 ;
    public static final int _lineType                   = 182 ;
    public static final int _lineFillBlip               = 183 ;
    public static final int _lineFillBlipFlags          = 184 ;
    public static final int _lineFillWidth              = 185 ;
    public static final int _lineFillHeight             = 186 ;
    public static final int _lineWidth                  = 187 ;
    public static final int _lineStyle                  = 188 ;
    public static final int _lineDashing                = 189 ;
    public static final int _lineStartArrowhead         = 190 ;
    public static final int _lineEndArrowhead           = 191 ;
    public static final int _lineStartArrowWidth        = 192 ;
    public static final int _lineStartArrowLength       = 193 ;
    public static final int _lineEndArrowWidth          = 194 ;
    public static final int _lineEndArrowLength         = 195 ;
    public static final int _fLine                      = 196 ;
    public static final int _lineCrMod                  = 198 ;
    public static final int _lineDashStyle              = 199 ;
    public static final int _lineEndCapStyle            = 200 ;
    public static final int _lineFillBlipName           = 201 ;
    public static final int _lineFillDztype             = 202 ;
    public static final int _lineJoinStyle              = 204 ;
    public static final int _lineMiterLimit             = 205 ;
    public static final int _fLineOK                    = 206 ;
    public static final int _shadowType                 = 207 ;
    public static final int _shadowColor                = 208 ;
    public static final int _shadowHighlight            = 209 ;
    public static final int _shadowOpacity              = 210 ;
    public static final int _shadowOffsetX              = 211 ;
    public static final int _shadowOffsetY              = 212 ;
    public static final int _shadowSecondOffsetX        = 213 ;
    public static final int _shadowSecondOffsetY        = 214 ;
    public static final int _shadowScaleXToX            = 215 ;
    public static final int _shadowScaleYToX            = 216 ;
    public static final int _shadowScaleXToY            = 217 ;
    public static final int _shadowScaleYToY            = 218 ;
    public static final int _shadowPerspectiveX         = 219 ;
    public static final int _shadowPerspectiveY         = 220 ;
    public static final int _shadowWeight               = 221 ;
    public static final int _shadowOriginX              = 222 ;
    public static final int _ShadowOriginY              = 223 ;
    public static final int _fShadow                    = 224 ;
    public static final int _shadowCrMod                = 225 ;
    public static final int _fshadowObscured            = 226 ;
    public static final int _fShadowOK                  = 227 ;
    public static final int _c3DSpecularAmt             = 228 ;
    public static final int _c3DDiffuseAmt              = 229 ;
    public static final int _c3DShininess               = 230 ;
    public static final int _c3DEdgeThickness           = 231 ;
    public static final int _c3DExtrudeForward          = 232 ;
    public static final int _c3DExtrudeBackward         = 233 ;
    public static final int _c3DExtrusionColor          = 234 ;
    public static final int _f3D                        = 235 ;
    public static final int _fc3DMetallic               = 236 ;
    public static final int _fc3DUseExtrusionColor      = 237 ;
    public static final int _fc3DLightFace              = 238 ;
    public static final int _c3DYRotationAngle          = 239 ;
    public static final int _c3DXRotationAngle          = 240 ;
    public static final int _c3DRotationAxisX           = 241 ;
    public static final int _c3DRotationAxisY           = 242 ;
    public static final int _c3DRotationAxisZ           = 243 ;
    public static final int _c3DRotationAngle           = 244 ;
    public static final int _fC3DRotationCenterAuto     = 245 ;
    public static final int _c3DRotationCenterX         = 246 ;
    public static final int _c3DRotationCenterY         = 247 ;
    public static final int _c3DRotationCenterZ         = 248 ;
    public static final int _c3DRenderMode              = 249 ;
    public static final int _c3DXViewpoint              = 250 ;
    public static final int _c3DYViewpoint              = 251 ;
    public static final int _c3DZViewpoint              = 252 ;
    public static final int _c3DOriginX                 = 253 ;
    public static final int _c3DOriginY                 = 254 ;
    public static final int _c3DSkewAngle               = 255 ;
    public static final int _c3DSkewAmount              = 256 ;
    public static final int _c3DAmbientIntensity        = 257 ;
    public static final int _c3DKeyX                    = 258 ;
    public static final int _c3DKeyY                    = 259 ;
    public static final int _c3DKeyZ                    = 260 ;
    public static final int _c3DKeyIntensity            = 261 ;
    public static final int _c3DFillX                   = 262 ;
    public static final int _c3DFillY                   = 263 ;
    public static final int _c3DFillZ                   = 264 ;
    public static final int _c3DFillIntensity           = 265 ;
    public static final int _fc3DParallel               = 266 ;
    public static final int _fc3DKeyHarsh               = 267 ;
    public static final int _fc3DFillHarsh              = 268 ;
    public static final int _c3DCrMod                   = 269 ;
    public static final int _c3DTolerance               = 270 ;
    public static final int _f3DOK                      = 271 ;
    public static final int _fc3DConstrainRotation      = 272 ;
    public static final int _perspectiveOffsetX         = 273 ;
    public static final int _perspectiveOffsetY         = 274 ;
    public static final int _perspectiveOriginX         = 275 ;
    public static final int _perspectiveOriginY         = 276 ;
    public static final int _perspectivePerspectiveX    = 277 ;
    public static final int _perspectivePerspectiveY    = 278 ;
    public static final int _perspectiveScaleXToX       = 279 ;
    public static final int _perspectiveScaleXToY       = 280 ;
    public static final int _perspectiveScaleYToX       = 281 ;
    public static final int _perspectiveScaleYToY       = 282 ;
    public static final int _perspectiveType            = 283 ;
    public static final int _perspectiveWeight          = 284 ;
    public static final int _fPerspective               = 285 ;
    public static final int _spcot                      = 286 ;
    public static final int _dxyCalloutGap              = 287 ;
    public static final int _spcoa                      = 288 ;
    public static final int _spcod                      = 289 ;
    public static final int _dxyCalloutDropSpecified    = 290 ;
    public static final int _dxyCalloutLengthSpecified  = 291 ;
    public static final int _fCallout                   = 292 ;
    public static final int _fCalloutAccentBar          = 293 ;
    public static final int _fCalloutTextBorder         = 294 ;
    public static final int _fCalloutDropAuto           = 295 ;
    public static final int _fCalloutLengthSpecified    = 296 ;
    public static final int _fCalloutMinusX             = 297 ;
    public static final int _fCalloutMinusY             = 298 ;
    public static final int _cxk                        = 300 ;
    public static final int _cxstyle                    = 301 ;
    public static final int _bWMode                     = 302 ;
    public static final int _bWModeBW                   = 303 ;
    public static final int _bWModePureBW               = 304 ;
    
}